name: biosegment
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  # backend
  - fastapi>=0.58.1
  - uvicorn>=0.11.3
  - sqlalchemy>=1.3.19
  - alembic>=1.4.2
  - psycopg2>=2.8.5
  - python-dotenv>=0.14.0
  # frontend
  - dash>=1.10.2
  - dash-bootstrap-components>=0.10.5
  - pandas>=1.1.0
  - pillow>=7.2.0
  - scikit-image>=0.16.2
  - pip>=20.2.2
  - pip:
    - "git+https://github.com/beehiveai/compose.git"
