name: celery_neuralnets
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
    # pytorch
  - pytorch
  - torchvision
  - cudatoolkit=10.2
    # celery
  - celery==4.4.6
  - watchdog
    # neuralnets
  - future
  - tensorboard
  - numpy
  - tifffile
  - h5py
  - scikit-image
  - progress
  - six
  - scikit-learn
  - opencv==4.2.0
  - pip
  - pip: 
    - git+https://github.com/JorisRoels/neuralnets.git@biosegment
    # celery
    - celery[redis]==4.4.6



