name: celery_neuralnets
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
    # celery
  - celery
  - tenacity
  - pip
  - pydantic
  - raven
  - psycopg2
  - requests
  - pip
  - pip:
    - pydantic[email]