name: celery_neuralnets
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
    # neuralnets
  - future
  - tensorboard
  - numpy
  - tifffile
  - h5py
  - scikit-image
  - progress
  - six
  - scikit-learn
  - opencv==4.2.0
  - pip
  - pip: 
    - git+https://github.com/JorisRoels/neuralnets.git@biosegment
  

