name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: biosegment_documentation
          environment-file: environment_documentation.yaml
          auto-activate-base: false
      - shell: bash -l {0}
        run: |
          mkdocs gh-deploy --force