name: GPU Worker testing
on: push
jobs:
    build-and-run:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Cache conda
            uses: actions/cache@v1
            env:
              # Increase this value to reset cache if etc/example-environment.yml has not changed
              CACHE_NUMBER: 0
            with:
              path: ~/conda_pkgs_dir
              key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('etc/example-environment.yml') }}
          - uses: conda-incubator/setup-miniconda@v1
            with:
              activate-environment: celery_neuralnets
              channel-priority: strict
              environment-file: gpu_worker/celery_all_environment.yml
              use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly!
          - name: Run GPU Worker
            shell: bash -l {0}
            run: |
              cd gpu_worker
              bash start_worker.sh