name: GPU Worker testing
on: push
jobs:
    build-and-run:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Update Conda environment with neuralnets requirements
          uses: actions/checkout@v2
          uses: matthewrmshin/conda-action@v1
          with:
            args: conda env update -f gpu_worker/celery_neuralnets_environment.yaml
        - name: Update Conda environment with celery requirements
          uses: matthewrmshin/conda-action@v1
          with:
            args: conda env update -f gpu_worker/celery_celery_environment.yaml
        - name: Update Conda environment with pytorch requirements
          uses: matthewrmshin/conda-action@v1
          with:
            args: conda env update -f gpu_worker/celery_pytorch_environment.yaml
        - name: Activate environment
          uses: matthewrmshin/conda-action@v1
          with:
            args: conda activate celery_neuralnets
        - name: Test GPU worker
          run: echo "TODO Add test code here"