name: BioSegment testing
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
  pull_request:
    branches:
      - master
jobs:
  # all jobs run in parallel by default
  lint:
    # run poetry to install dev dependencies for backend lint script
    strategy:
      fail-fast: false
      matrix:
        # linting on one platform is sufficient
        python-version: [3.7]
        poetry-version: [1.0.10]
        # os: [ubuntu-18.04, macos-latest, windows-latest]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Set up cache
        uses: actions/cache@v1
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/pyproject.toml', '**/poetry.lock') }}
      - name: Install dependencies
        run: |
          cd backend/app
          poetry install
      - name: Run test
        run: |
          cd backend/app
          poetry run sh scripts/lint.sh
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - name: Test BioSegment
      # use sh to avoid permission errors
        run: sh ./scripts/test.sh
