name: BioSegment testing
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
  pull_request:
    branches:
      - master
jobs:
  # all jobs run in parallel by default
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Run linter
        run: echo "Linting TODO"
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - name: Test BioSegment
        run: ./scripts/test.sh
        shell: bash
